In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
df=pd.read_excel("Final_Train.xlsx")

In [3]:
df.shape

(5961, 7)

In [4]:
df1=pd.read_excel("Final_Test.xlsx")

In [5]:
df1.shape

(1987, 6)

In [6]:
set(df1["Profile"]).difference(set(df["Profile"]))

set()

In [7]:
full=pd.concat([df,df1],ignore_index=True)

C:\Users\skbra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [8]:
miss=[]
for i, row in full.iterrows():
    miss.append(re.sub('[,]', ' ', str(row["Miscellaneous_Info"])))

In [9]:
full["Miss"]=miss

In [10]:
from nltk.corpus import stopwords
import string
import re
import nltk
from nltk.stem.porter import PorterStemmer

In [11]:
missi=[]
for i, row in full.iterrows():
    missi.append(re.sub('[,/]', '', str(row["Miscellaneous_Info"])))

In [12]:
full["missi"]=missi

In [13]:
missi1=[]
for i, row in full.iterrows():
    missi1.append(re.sub(' +', ' ', str(row["missi"])))

In [14]:
full["Missi1"]=missi1

In [15]:
full["Missi1"].replace("nan","####",inplace=True)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv1 = CountVectorizer(max_features=200)
y = cv1.fit_transform(full["Missi1"]).toarray()

In [17]:
len(cv1.vocabulary_)

200

In [18]:
y.shape

(7948, 200)

In [19]:
thirty= list(y)
thirty1=pd.DataFrame(thirty)

In [20]:
qual=[]
for i, row in full.iterrows():
    qual.append(re.sub('[,]', ' ', str(row["Qualification"])))

In [21]:
full["Qual"]=qual

In [22]:
qual1=[]
for i, row in full.iterrows():
    qual1.append(re.sub('[-]', '', str(row["Qual"])))

In [23]:
full["Qual1"]=qual1

In [24]:
qual2=[]
for i, row in full.iterrows():
    qual2.append(re.sub(' +', ' ', str(row["Qual1"])))

In [25]:
full["Qual2"]=qual2

In [26]:
#full["Qual2"]

In [27]:
full["Qual2"].replace("nan","####",inplace=True)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=50)
X = cv.fit_transform(full["Qual2"]).toarray()

In [29]:
twenty= list(X)
twenty1=pd.DataFrame(twenty)

In [30]:
#plt.figure(figsize=(25,25))
#sns.distplot(df["Fees"])

In [31]:
#df.isna().sum()

In [32]:
#df.shape

In [33]:
#df["Rating1"].value_counts().sort_values()

In [34]:
#plt.figure(figsize=(25,25))
#sns.lineplot(x="Rating_",y="Fees",data=df)

In [35]:
#df["Experience"].value_counts()

In [36]:
Rating1=[]
for i, row in df.iterrows():
    Rating1.append(re.sub('[%]', '', str(row["Rating"])))

In [37]:
Rating1test=[]
for i, row in df1.iterrows():
    Rating1test.append(re.sub('[%]', '', str(row["Rating"])))

In [38]:
Rating_=[]
for i in range(0,len(Rating1)):
    Rating_.append(float(Rating1[i]))

In [39]:
Rating_test=[]
for i in range(0,len(Rating1test)):
    Rating_test.append(float(Rating1test[i]))

In [40]:
df["Rating_"]=Rating_

In [41]:
df1["Rating_"]=Rating_test

In [42]:
df["Rating_NA"]=df["Rating"].isna()

In [43]:
df1["Rating_NA"]=df1["Rating"].isna()

In [44]:
df['Rating_'].fillna(int(-999),inplace=True)

In [45]:
df1['Rating_'].fillna(int(-999),inplace=True)

In [46]:
#sns.barplot(x="Profile",y="Fees", data=df)

In [47]:
#df[df["Rating_"]==76]

In [48]:
Experience1=[]
for i, row in df.iterrows():
    Experience1.append(re.sub('[ years experience]', '', str(row["Experience"])))

In [49]:
Experience1test=[]
for i, row in df1.iterrows():
    Experience1test.append(re.sub('[ years experience]', '', str(row["Experience"])))

In [50]:
Experience_=[]
for i in range(0,len(Experience1)):
    Experience_.append(float(Experience1[i]))

In [51]:
Experience_test=[]
for i in range(0,len(Experience1test)):
    Experience_test.append(float(Experience1test[i]))

In [52]:
df["Experience_"]=Experience_

In [53]:
df1["Experience_"]=Experience_test

In [54]:
#df

In [55]:
#plt.figure(figsize=(25,25))
#sns.lineplot(x="Experience_",y="Fees",data=df)

In [56]:
#sns.barplot(x="Experience_",y="Fees")

In [57]:
#df["Qualification"].value_counts()

In [58]:
#df["Place"].value_counts()

In [59]:
lol=df["Place"].str.split(", ",n=1,expand=True)

In [60]:
df["Location"]=lol[0]

In [61]:
df["City"]=lol[1]

In [62]:
lol1=df1["Place"].str.split(", ",n=1,expand=True)

In [63]:
df1["Location"]=lol1[0]

In [64]:
df1["City"]=lol1[1]

In [65]:
#sns.barplot(x="City",y="Fees",data=df)

In [66]:
#plt.figure(figsize=(25,25))
#sns.barplot(x="Location",y="Fees",data=df)

In [67]:
#lol2=df["Qualification"].str.split(", ",n=1,expand=True)

In [68]:
#df["Qual1"]=lol2[0]

In [69]:
#df["Qual2"]=lol2[1]

In [70]:
#lol3=df1["Qualification"].str.split(", ",n=1,expand=True)

In [71]:
#df1["Qual1"]=lol3[0]

In [72]:
#df1["Qual2"]=lol3[1]

In [73]:
#set(df1["Location"]).intersection(set(df["Location"]))

In [74]:
#df1[df1["Location"]=="Lingarajapuram"]

In [75]:
#df1[(df1.City=="Delhi") & (df1.Profile=="ENT Specialist")]

In [76]:
#df1[(df1.City=="Delhi") & (df1.Profile=="ENT Specialist") & (df1.Location=="Saket")]

In [77]:
#df[(df.City=="Delhi") & (df.Profile=="ENT Specialist")]["Location"].value_counts()

In [78]:
#df[(df.City=="Delhi") & (df.Profile=="ENT Specialist") & (df.Location=="Shalimar Bagh")]

In [79]:
#df["Qual2"].split()

In [80]:
#set(df1["Location"]).difference(set(df["Location"]))

In [81]:
unknownlocation=['Alipur',
 'Aroor',
 'Ayanambakkam',
 'Ayyappankavu',
 'BHEL',
 'Bachupally',
 'Bhandup',
 'Bhogal',
 'Burari',
 'Chandrayangutta',
 'Cheranalloor',
 'Chickpet',
 'Choolai',
 'Delhi Cantonment',
 'Dindarpur',
 'Dwarka Sector 12',
 'Ernakulam',
 'Gamdevi',
 'Hasthinapuram',
 'Hastsal',
 'Hongasandra',
 'Hosur Road',
 'Iyyappanthangal',
 'JP Nagar 9 Phase',
 'Jafferkhanpet',
 'Jayanagar 2 Block',
 'KH Road',
 'Kadubeesanahalli',
 'Kalu Sarai',
 'Kanjoor',
 'Kapra',
 'Kaudiar',
 'Khar East',
 'Koramangala 7 Block',
 'Kudlu',
 'Kurla',
 'Lingarajapuram',
 'Madambakkam',
 'Madhavaram',
 'Mahavir Enclave',
 'Mahipalpur',
 'Manchavilakom',
 'Meerpet',
 'Nacharam',
 'Nandambakkam',
 'Nedumangad',
 'Nedumbassery',
 'Nemom',
 'Outer Ring Road',
 'Padi',
 'Palghar',
 'Pattabiram',
 'Periyanaickenpalayam',
 'Poothotta',
 'Pratap Nagar',
 'Ramakrishna Puram',
 'Rohini Sector 20',
 'Rohini West',
 'Safilguda',
 'Sagar Road',
 'Sarvapriya Vihar',
 'Seeranaickenpalayam',
 'Sewri',
 'Shadipur',
 'Sriniwaspuri',
 'Tavarekere',
 'Tv Thampanoor',
 'Vikas Nagar',
 'Vishwas Nagar',
 'Warasiguda',
 'Yemalur']

In [82]:
twentytrain=twenty1.iloc[0:5961,:]

In [83]:
twentytest=twenty1.iloc[5961:7949,:]

In [84]:
thritytrain1=thirty1.iloc[0:5961,:]

In [85]:
thritytest1=thirty1.iloc[5961:7949,:]

In [86]:
thritytest1.reset_index(drop=True,inplace=True)

In [87]:
twentytest.reset_index(drop=True,inplace=True)

In [88]:
df=pd.concat([df,twentytrain,thritytrain1],axis=1,ignore_index=True)

In [89]:
lol=pd.concat([df1,twentytest,thritytest1],axis=1,ignore_index=True)

In [90]:
#lol.iloc[:,0:10]

In [91]:
#df.iloc[:,0:10]

In [92]:
samekey=pd.DataFrame()

In [93]:
for i in range(0,len(unknownlocation)):
    lol1=lol[lol[9] == unknownlocation[i]]
    samekey=pd.concat([samekey,lol1],axis=0)

In [94]:
for i in range(0,len(unknownlocation)):
    lol=lol[lol[9] != unknownlocation[i]]

In [95]:
samekey

,0,1,2,3,4,5,6,7,8,9,...,251,252,253,254,255,256,257,258,259,260
715,BHMS,5 years experience,NaN,"Alipur, Delhi",Homeopath,NaN,-999.0,True,5.0,Alipur,...,0,0,0,0,0,0,0,0,0,0
131,"MBBS, Diploma in Orthopaedics",23 years experience,NaN,"Aroor, Ernakulam",General Medicine,NaN,-999.0,True,23.0,Aroor,...,0,0,0,0,0,0,0,0,0,0
453,"MBBS, Diploma in Tuberculosis and Chest Diseas...",10 years experience,NaN,"Ayanambakkam, Chennai",General Medicine,NaN,-999.0,True,10.0,Ayanambakkam,...,0,0,0,0,0,0,0,0,0,0
1721,BDS,14 years experience,99%,"Ayyappankavu, Ernakulam",Dentist,Biomimetic Dentistry RCT - Root Canal Treatmen...,99.0,False,14.0,Ayyappankavu,...,0,0,0,0,0,0,0,0,0,0
1907,BHMS,14 years experience,NaN,"BHEL, Hyderabad",Homeopath,NaN,-999.0,True,14.0,BHEL,...,0,0,0,0,0,0,0,0,0,0
1083,"BDS, Master of Public Health (MPH)",9 years experience,100%,"Bachupally, Hyderabad",Dentist,Dental X-Ray Dental Crowns BPS Dentures Fixing,100.0,False,9.0,Bachupally,...,0,0,0,0,0,0,0,0,0,0
209,BAMS,24 years experience,NaN,"Bhandup, Mumbai",Ayurveda,NaN,-999.0,True,24.0,Bhandup,...,0,0,0,0,0,0,0,0,0,0
951,"MD - Dermatology, MBBS",7 years experience,98%,"Bhogal, Delhi",Dermatologists,"98% 221 Feedback Bhogal, Delhi",98.0,False,7.0,Bhogal,...,0,0,0,0,0,0,0,0,0,0
1036,"MBBS, DDVL, Certificate of Completion of Speci...",13 years experience,94%,"Burari, Delhi",Dermatologists,"94% 68 Feedback Burari, Delhi",94.0,False,13.0,Burari,...,0,0,0,0,0,0,0,0,0,0
91,"MBBS, MS - ENT",29 years experience,83%,"Chandrayangutta, Hyderabad",ENT Specialist,"83% 3 Feedback Chandrayangutta, Hyderabad",83.0,False,29.0,Chandrayangutta,...,0,0,0,0,0,0,0,0,0,0
445,"MBBS, MCh - Surgical Gastroenterology/G.I. Sur...",9 years experience,NaN,"Cheranalloor, Ernakulam",General Medicine,NaN,-999.0,True,9.0,Cheranalloor,...,0,0,0,0,0,0,0,0,0,0
248,MBBS,6 years experience,84%,"Chickpet, Bangalore",General Medicine,"84% 10 Feedback Chickpet, Bangalore",84.0,False,6.0,Chickpet,...,0,0,0,0,0,0,0,0,0,0
913,"MBBS, DNB - General Medicine",10 years experience,93%,"Chickpet, Bangalore",General Medicine,"93% 14 Feedback Chickpet, Bangalore",93.0,False,10.0,Chickpet,...,0,0,0,0,0,0,0,0,0,0
1588,BAMS,21 years experience,NaN,"Chickpet, Bangalore",Ayurveda,NaN,-999.0,True,21.0,Chickpet,...,0,0,0,0,0,0,0,0,0,0
1965,"MBBS, MRCOG(UK)",35 years experience,88%,"Choolai, Chennai",General Medicine,"88% 5 Feedback Choolai, Chennai",88.0,False,35.0,Choolai,...,0,0,0,0,0,0,0,0,0,0
1983,"MD - Dermatology , Venereology & Leprosy, MBBS",4 years experience,NaN,"Choolai, Chennai",Dermatologists,NaN,-999.0,True,4.0,Choolai,...,0,0,0,0,0,0,0,0,0,0
1507,"MBBS, MS - Otorhinolaryngology, MS - ENT",16 years experience,100%,"Delhi Cantonment, Delhi",ENT Specialist,"100% 12 Feedback Delhi Cantonment, Delhi",100.0,False,16.0,Delhi Cantonment,...,0,0,0,0,0,0,0,0,0,0
472,BAMS,34 years experience,NaN,"Dindarpur, Delhi",Ayurveda,NaN,-999.0,True,34.0,Dindarpur,...,0,0,0,0,0,0,0,0,0,0
1869,BHMS,24 years experience,NaN,"Dwarka Sector 12, Delhi",Homeopath,NaN,-999.0,True,24.0,Dwarka Sector 12,...,0,0,0,0,0,0,0,0,0,0
95,"MDS - Conservative Dentistry & Endodontics, BDS",11 years experience,100%,"Ernakulam, Ernakulam",Dentist,"100% 1 Feedback Ernakulam, Ernakulam",100.0,False,11.0,Ernakulam,...,0,0,0,0,0,0,0,0,0,0
1359,MBBS,34 years experience,NaN,"Gamdevi, Mumbai",General Medicine,NaN,-999.0,True,34.0,Gamdevi,...,0,0,0,0,0,0,0,0,0,0
1885,"MBBS, DM - Cardiology, MD - Medicine",34 years experience,100%,"Gamdevi, Mumbai",General Medicine,"100% 25 Feedback Gamdevi, Mumbai",100.0,False,34.0,Gamdevi,...,0,0,0,0,0,0,0,0,0,0
1532,MBBS,40 years experience,NaN,"Hasthinapuram, Chennai",General Medicine,NaN,-999.0,True,40.0,Hasthinapuram,...,0,0,0,0,0,0,0,0,0,0
1871,"MBBS, Post Graduate Diploma in Family Medicine...",10 years experience,NaN,"Hasthinapuram, Chennai",General Medicine,NaN,-999.0,True,10.0,Hasthinapuram,...,0,0,0,0,0,0,0,0,0,0
857,"BDS, B.Sc - Zoology (Hons.)",31 years experience,100%,"Hastsal, Delhi",Dentist,Dental X-Ray Dental prophylaxis Dental Fillings,100.0,False,31.0,Hastsal,...,0,0,0,0,0,0,0,0,0,0
1849,BHMS,11 years experience,NaN,"Hongasandra, Bangalore",Homeopath,NaN,-999.0,True,11.0,Hongasandra,...,0,0,0,0,0,0,0,0,0,0
1956,BDS,0 years experience,NaN,"Hosur Road, Bangalore",Dentist,Orthotic Splints Disclusion Time Reduction (DT...,-999.0,True,0.0,Hosur Road,...,1,0,0,0,0,0,0,0,0,0
552,MBBS,6 years experience,NaN,"Iyyappanthangal, Chennai",General Medicine,NaN,-999.0,True,6.0,Iyyappanthangal,...,0,0,0,0,0,0,0,0,0,0
1068,"MBBS, Diploma in Otorhinolaryngology (DLO)",12 years experience,100%,"JP Nagar 9 Phase, Bangalore",ENT Specialist,"100% 9 Feedback JP Nagar 9 Phase, Bangalore",100.0,False,12.0,JP Nagar 9 Phase,...,0,0,0,0,0,0,0,0,0,0
1114,BDS,15 years experience,100%,"Jafferkhanpet, Chennai",Dentist,Artificial Teeth Impaction / Impacted Tooth Ex...,100.0,False,15.0,Jafferkhanpet,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1812,BDS,25 years experience,98%,"Nacharam, Hyderabad",Dentist,Dental Crowns Crowns and Bridges Fixing Cosmet...,98.0,False,25.0,Nacharam,...,0,0,0,0,0,0,0,0,0,0
1172,"MBBS, MD - Internal Medicine",24 years experience,92%,"Nandambakkam, Chennai",General Medicine,"92% 2 Feedback Nandambakkam, Chennai",92.0,False,24.0,Nandambakkam,...,0,0,0,0,0,0,0,0,0,0
990,"BDS, MDS - Prosthodontics",20 years experience,91%,"Nedumangad, Thiruvananthapuram",Dentist,"91% 8 Feedback Nedumangad, Thiruvananthapuram",91.0,False,20.0,Nedumangad,...,0,0,0,0,0,0,0,0,0,0
777,BAMS,29 years experience,NaN,"Nedumbassery, Ernakulam",Ayurveda,NaN,-999.0,True,29.0,Nedumbassery,...,0,0,0,0,0,0,0,0,0,0
651,"BDS, MDS-Oral Pathology and Oral Microbiology",18 years experience,NaN,"Nemom, Thiruvananthapuram",Dentist,NaN,-999.0,True,18.0,Nemom,...,0,0,0,0,0,0,0,0,0,0
946,"MBBS, MS - ENT",14 years experience,89%,"Outer Ring Road, Bangalore",ENT Specialist,"89% 1 Feedback Outer Ring Road, Bangalore",89.0,False,14.0,Outer Ring Road,...,0,0,0,0,0,0,0,0,0,0
1699,MDS,23 years experience,99%,"Padi, Chennai",Dentist,NaN,99.0,False,23.0,Padi,...,0,0,0,0,0,0,0,0,0,0
1272,"BAMS, MD - Ayurveda Medicine",10 years experience,NaN,"Palghar, Mumbai",Ayurveda,NaN,-999.0,True,10.0,Palghar,...,0,0,0,0,0,0,0,0,0,0
583,"MBBS, Diploma in Otorhinolaryngology (DLO)",18 years experience,NaN,"Pattabiram, Chennai",ENT Specialist,NaN,-999.0,True,18.0,Pattabiram,...,0,0,0,0,0,0,0,0,0,0
1603,BDS,4 years experience,NaN,"Periyanaickenpalayam, Coimbatore",Dentist,NaN,-999.0,True,4.0,Periyanaickenpalayam,...,0,0,0,0,0,0,0,0,0,0
1374,"BDS, MDS - Oral & Maxillofacial Surgery",3 years experience,NaN,"Poothotta, Ernakulam",Dentist,NaN,-999.0,True,3.0,Poothotta,...,0,0,0,0,0,0,0,0,0,0
1772,"MD - Dermatology, MBBS",9 years experience,100%,"Pratap Nagar, Delhi",Dermatologists,"100% 8 Feedback Pratap Nagar, Delhi",100.0,False,9.0,Pratap Nagar,...,0,0,0,0,0,0,0,0,0,0
61,MBBS,32 years experience,NaN,"Ramakrishna Puram, Hyderabad",General Medicine,NaN,-999.0,True,32.0,Ramakrishna Puram,...,0,0,0,0,0,0,0,0,0,0
1175,BHMS,8 years experience,NaN,"Rohini Sector 20, Delhi",Homeopath,NaN,-999.0,True,8.0,Rohini Sector 20,...,0,0,0,0,0,0,0,0,0,0
158,"MBBS, Diploma in Anesthesiology, Certificate i...",17 years experience,100%,"Rohini West, Delhi",General Medicine,"100% 10 Feedback Rohini West, Delhi",100.0,False,17.0,Rohini West,...,0,0,0,0,0,1,0,0,0,0
804,"MBBS, MD - Internal Medicine",12 years experience,NaN,"Safilguda, Hyderabad",General Medicine,NaN,-999.0,True,12.0,Safilguda,...,0,0,0,0,0,0,0,0,0,0
1304,"BDS, PhD - Orthodontics & Dentofacial Orthopae...",13 years experience,95%,"Sagar Road, Hyderabad",Dentist,Tooth Extraction Dental Fillings Scaling / Pol...,95.0,False,13.0,Sagar Road,...,0,0,0,0,0,0,0,0,0,0
582,"BDS, MDS - Conservative Dentistry & Endodontics",18 years experience,98%,"Sarvapriya Vihar, Delhi",Dentist,Endo Surgery Or Apicoectomy Mucogingival Surge...,98.0,False,18.0,Sarvapriya Vihar,...,0,0,0,0,0,0,0,0,0,0
1049,"MBBS, MS - MS.Medicine",34 years experience,NaN,"Seeranaickenpalayam, Coimbatore",General Medicine,NaN,-999.0,True,34.0,Seeranaickenpalayam,...,0,0,0,0,0,0,0,0,0,0
1691,MBBS,40 years experience,NaN,"Sewri, Mumbai",General Medicine,NaN,-999.0,True,40.0,Sewri,...,0,0,0,0,0,0,0,0,0,0
1806,BAMS,37 years experience,NaN,"Shadipur, Delhi",Ayurveda,NaN,-999.0,True,37.0,Shadipur,...,0,0,0,0,0,0,0,0,0,0
1227,"BDS, Certificate in Orthodontics",13 years experience,92%,"Sriniwaspuri, Delhi",Dentist,Dental Crowns Dental X-Ray Dental Fillings,92.0,False,13.0,Sriniwaspuri,...,0,0,0,0,0,0,0,0,0,0
372,"MBBS, MD - General Medicine",24 years experience,90%,"Tavarekere, Bangalore",General Medicine,NaN,90.0,False,24.0,Tavarekere,...,0,0,0,0,0,0,0,0,0,0
865,BAMS,6 years experience,NaN,"Tv Thampanoor, Thiruvananthapuram",Ayurveda,NaN,-999.0,True,6.0,Tv Thampanoor,...,0,0,0,0,0,0,0,0,0,0
65,"MBBS, MS - ENT, Diploma in Otorhinolaryngology...",41 years experience,69%,"Vikas Nagar, Delhi",ENT Specialist,"69% 3 Feedback Vikas Nagar, Delhi",69.0,False,41.0,Vikas Nagar,...,0,0,0,0,0,0,0,0,0,0
177,"MBBS, MD - Obstetrics & Gynaecology",36 years experience,NaN,"Vishwas Nagar, Delhi",General Medicine,NaN,-999.0,True,36.0,Vishwas Nagar,...,0,0,0,0,0,0,0,0,0,0
163,BAMS,38 years experience,NaN,"Warasiguda, Hyderabad",Ayurveda,NaN,-999.0,True,38.0,Warasiguda,...,0,0,0,0,0,0,0,0,0,0
417,"MBBS, MD - General Medicine",40 years experience,94%,"Warasiguda, Hyderabad",General Medicine,"94% 5 Feedback Warasiguda, Hyderabad",94.0,False,40.0,Warasiguda,...,0,0,0,0,0,0,0,0,0,0
560,"MBBS, MS - ENT",38 years experience,NaN,"Warasiguda, Hyderabad",ENT Specialist,NaN,-999.0,True,38.0,Warasiguda,...,0,0,0,0,0,0,0,0,0,0
1641,"BHMS, Certificate Course in Advanced Homoeopat...",7 years experience,100%,"Yemalur, Bangalore",Homeopath,"100% 10 Feedback Yemalur, Bangalore",100.0,False,7.0,Yemalur,...,0,0,0,0,0,0,0,0,0,0

In [96]:
lol.loc[710:720,:]

,0,1,2,3,4,5,6,7,8,9,...,251,252,253,254,255,256,257,258,259,260
710,"BAMS, MD - Ayurveda Medicine",12 years experience,98%,"AS Rao Nagar, Hyderabad",Ayurveda,"98% 26 Feedback AS Rao Nagar, Hyderabad",98.0,False,12.0,AS Rao Nagar,...,0,0,0,0,0,0,0,0,0,0
711,"MBBS, MD - General Medicine",28 years experience,100%,"Somajiguda, Hyderabad",General Medicine,"100% 2 Feedback Somajiguda, Hyderabad",100.0,False,28.0,Somajiguda,...,0,0,0,0,0,0,0,0,0,0
712,"MBBS, MS - ENT",38 years experience,NaN,"Shalimar Bagh, Delhi",ENT Specialist,Hearing Deficiency Assessment Congenital Ear P...,-999.0,True,38.0,Shalimar Bagh,...,0,0,0,0,0,0,0,0,0,0
713,"DNB - General Medicine, MBBS",5 years experience,NaN,"LB Nagar, Hyderabad",General Medicine,Type 2 Diabetes Treatment Infectious Disease T...,-999.0,True,5.0,LB Nagar,...,0,0,0,0,0,0,0,0,0,0
714,"MBBS, MD - Dermatology, DNB - Dermatology & Ve...",14 years experience,99%,"Matunga, Mumbai",Dermatologists,"99% 43 Feedback Matunga, Mumbai",99.0,False,14.0,Matunga,...,0,0,0,0,0,0,0,0,0,0
716,BDS,17 years experience,100%,"Kandivali West, Mumbai",Dentist,Dental Implant Fixing Crowns and Bridges Fixin...,100.0,False,17.0,Kandivali West,...,0,0,0,0,0,0,0,0,0,0
717,"MBBS, DNB",19 years experience,NaN,"Greater Kailash Part 2, Delhi",General Medicine,Abdominal Pain Treatment Sebaceous cyst excisi...,-999.0,True,19.0,Greater Kailash Part 2,...,0,0,0,0,0,0,0,0,0,0
718,"BDS, MDS - Paedodontics And Preventive Dentistry",8 years experience,100%,"Dwarka, Delhi",Dentist,"100% 60 Feedback Dwarka, Delhi",100.0,False,8.0,Dwarka,...,0,0,0,0,0,0,0,0,0,0
719,MD - Homeopathy,6 years experience,NaN,"Ghatkopar East, Mumbai",Homeopath,NaN,-999.0,True,6.0,Ghatkopar East,...,0,0,0,0,0,0,0,0,0,0
720,BAMS,27 years experience,NaN,"Vikhroli, Mumbai",Ayurveda,NaN,-999.0,True,27.0,Vikhroli,...,0,0,0,0,0,0,0,0,0,0

In [97]:
at=pd.concat([samekey,lol],axis=0)

In [98]:
at1=at.sort_index(axis=0)

In [99]:
at1.iloc[700:720,:]

,0,1,2,3,4,5,6,7,8,9,...,251,252,253,254,255,256,257,258,259,260
700,"BDS, MDS",23 years experience,97%,"Andheri West, Mumbai",Dentist,Dental Implant Fixing Cast Partial Denture BPS...,97.0,False,23.0,Andheri West,...,0,0,0,0,0,0,0,0,0,0
701,"MBBS, MD - Dermatology",29 years experience,NaN,"Greams Road, Chennai",Dermatologists,NaN,-999.0,True,29.0,Greams Road,...,0,0,0,0,0,0,0,0,0,0
702,"BDS, Certification in Aesthetic Dentistry",19 years experience,99%,"Jayamahal, Bangalore",Dentist,Crowns and Bridges Fixing Complete/Partial Den...,99.0,False,19.0,Jayamahal,...,0,0,0,0,0,0,0,0,0,0
703,BDS,6 years experience,NaN,"Borivali West, Mumbai",Dentist,Crowns and Bridges Fixing Artificial Teeth Cos...,-999.0,True,6.0,Borivali West,...,0,0,0,0,0,0,0,0,0,0
704,"MDS - Prosthodontist And Crown Bridge, BDS",19 years experience,100%,"Preet Vihar, Delhi",Dentist,"100% 4 Feedback Preet Vihar, Delhi",100.0,False,19.0,Preet Vihar,...,0,1,0,0,0,0,0,0,0,0
705,BDS,24 years experience,96%,"Secunderabad, Hyderabad",Dentist,Acrylic Partial Denture Artificial Teeth Impac...,96.0,False,24.0,Secunderabad,...,0,0,0,0,0,0,0,0,0,0
706,"MBBS, MD - Homeopathy, MD - General Medicine",35 years experience,NaN,"Adyar, Chennai",Homeopath,NaN,-999.0,True,35.0,Adyar,...,0,0,0,0,0,0,0,0,0,0
707,MBBS,19 years experience,NaN,"Naraina Vihar, Delhi",General Medicine,NaN,-999.0,True,19.0,Naraina Vihar,...,0,0,0,0,0,0,0,0,0,0
708,BDS,5 years experience,100%,"Vileparle East, Mumbai",Dentist,Ceramic Veneers / Crowns Tooth Extraction Dent...,100.0,False,5.0,Vileparle East,...,1,0,0,0,0,0,0,0,0,0
709,"MDS - Pedodontics, BDS",24 years experience,95%,"Edapally, Ernakulam",Dentist,"95% 3 Feedback Edapally, Ernakulam",95.0,False,24.0,Edapally,...,0,0,0,0,0,0,0,0,0,0
710,"BAMS, MD - Ayurveda Medicine",12 years experience,98%,"AS Rao Nagar, Hyderabad",Ayurveda,"98% 26 Feedback AS Rao Nagar, Hyderabad",98.0,False,12.0,AS Rao Nagar,...,0,0,0,0,0,0,0,0,0,0
711,"MBBS, MD - General Medicine",28 years experience,100%,"Somajiguda, Hyderabad",General Medicine,"100% 2 Feedback Somajiguda, Hyderabad",100.0,False,28.0,Somajiguda,...,0,0,0,0,0,0,0,0,0,0
712,"MBBS, MS - ENT",38 years experience,NaN,"Shalimar Bagh, Delhi",ENT Specialist,Hearing Deficiency Assessment Congenital Ear P...,-999.0,True,38.0,Shalimar Bagh,...,0,0,0,0,0,0,0,0,0,0
713,"DNB - General Medicine, MBBS",5 years experience,NaN,"LB Nagar, Hyderabad",General Medicine,Type 2 Diabetes Treatment Infectious Disease T...,-999.0,True,5.0,LB Nagar,...,0,0,0,0,0,0,0,0,0,0
714,"MBBS, MD - Dermatology, DNB - Dermatology & Ve...",14 years experience,99%,"Matunga, Mumbai",Dermatologists,"99% 43 Feedback Matunga, Mumbai",99.0,False,14.0,Matunga,...,0,0,0,0,0,0,0,0,0,0
715,BHMS,5 years experience,NaN,"Alipur, Delhi",Homeopath,NaN,-999.0,True,5.0,Alipur,...,0,0,0,0,0,0,0,0,0,0
716,BDS,17 years experience,100%,"Kandivali West, Mumbai",Dentist,Dental Implant Fixing Crowns and Bridges Fixin...,100.0,False,17.0,Kandivali West,...,0,0,0,0,0,0,0,0,0,0
717,"MBBS, DNB",19 years experience,NaN,"Greater Kailash Part 2, Delhi",General Medicine,Abdominal Pain Treatment Sebaceous cyst excisi...,-999.0,True,19.0,Greater Kailash Part 2,...,0,0,0,0,0,0,0,0,0,0
718,"BDS, MDS - Paedodontics And Preventive Dentistry",8 years experience,100%,"Dwarka, Delhi",Dentist,"100% 60 Feedback Dwarka, Delhi",100.0,False,8.0,Dwarka,...,0,0,0,0,0,0,0,0,0,0
719,MD - Homeopathy,6 years experience,NaN,"Ghatkopar East, Mumbai",Homeopath,NaN,-999.0,True,6.0,Ghatkopar East,...,0,0,0,0,0,0,0,0,0,0

In [100]:
#from sklearn.preprocessing import LabelEncoder
#lbl=LabelEncoder()
#lbl.fit(df["Qualification"])

In [101]:
#lbl.transform(df1["Qualification"])

In [102]:
#set(df1["Qual2"]).difference(set(df["Qual2"]))

In [103]:
#df[df["Qual2"]=='BDS, MDS']

In [104]:
#df[df["Qual2"]=="MD - Physician, DNB - General Medicine, Fellowship in Diabetology"]

In [105]:
#df1["Qual1"].unique()

In [106]:
df.drop([0,1,2,3,5],axis=1,inplace=True)

In [107]:
lol.drop([0,1,2,3,5],axis=1,inplace=True)

In [108]:
samekey.drop([0,1,2,3,5], axis=1, inplace=True)

In [109]:
#df.drop("Place",axis=1,inplace=True)

In [110]:
#df.head()

In [111]:
#df.isna().sum()

In [112]:
#df["Qual2"].fillna("Nothing",inplace=True)

In [113]:
#df1["Qual2"].fillna("Nothing",inplace=True)

In [114]:
df1=lol
df2=samekey

In [115]:
df["LocationNA"]=df[10].isna()

In [116]:
df1["LocationNA"]=df1[9].isna()
df2["LocationNA"]=df2[9].isna()

In [117]:
df["CityNA"]=df[11].isna()

In [118]:
df1["CityNA"]=df1[10].isna()
df2["CityNA"]=df2[10].isna()

In [119]:
df[11].fillna("UnknownCity",inplace=True)

In [120]:
df1[10].fillna("UnknownCity",inplace=True)
df2[10].fillna("UnknownCity",inplace=True)

In [121]:
df[10].fillna("UnknownLocation",inplace=True)

In [122]:
df1[9].fillna("UnknownLocation",inplace=True)
df2[9].fillna("UnknownLocation",inplace=True)

In [123]:
groupbylocation=df.groupby(10)[6].mean()
df['LOCDmean']=df[10].map(groupbylocation)
df1['LOCDmean']=df1[9].map(groupbylocation)
df2['LOCDmean']=df2[9].map(groupbylocation)

In [124]:
groupbycity=df.groupby(11)[6].mean()
df['Citymean']=df[11].map(groupbycity)
df1['Citymean']=df1[10].map(groupbycity)
df2['Citymean']=df2[10].map(groupbycity)

In [125]:
#df1["Profile"]

In [126]:
#groupbyQualification1=df.groupby('Qual1')['Fees'].mean()
#df['Qualification1mean']=df['Qual1'].map(groupbyQualification1)
#df1['Qualification1mean']=df1['Qual1'].map(groupbyQualification1)

In [127]:
#groupbyQualification2=df.groupby('Qual2')['Fees'].mean()
#df['Qualification2mean']=df['Qual2'].map(groupbyQualification2)
#df1['Qualification2mean']=df1['Qual2'].map(groupbyQualification2)

In [128]:
#df.drop(["Location","LocationNA"],axis=1,inplace=True)
#df1.drop(["Location","LocationNA"],axis=1,inplace=True)

In [129]:
#df.drop(["Qual2"],axis=1,inplace=True)
#df1.drop(["Qual2"],axis=1,inplace=True)

In [130]:
#df.isnull().sum()

In [131]:
X=df.drop(6,axis=1)

In [132]:
X1 = df.drop(6, axis=1)

In [133]:
y=df[6]

In [134]:
test=df1

In [135]:
test1=df2

In [136]:
X.columns=range(X.shape[1])

In [137]:
test.columns=range(test.shape[1])

In [138]:
X

,0,1,2,3,4,5,6,7,8,9,...,250,251,252,253,254,255,256,257,258,259
0,Homeopath,100.0,False,24.0,Kakkanad,Ernakulam,0,0,0,0,...,0,0,0,0,0,0,False,False,186.153846,188.431373
1,Ayurveda,98.0,False,12.0,Whitefield,Bangalore,0,0,1,1,...,0,0,1,0,0,0,False,False,398.936170,328.842607
2,ENT Specialist,-999.0,True,9.0,Mathikere - BEL,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,268.181818,328.842607
3,Ayurveda,-999.0,True,12.0,Bannerghatta Road,Bangalore,0,0,0,1,...,0,0,0,0,0,0,False,False,410.256410,328.842607
4,Ayurveda,100.0,False,20.0,Keelkattalai,Chennai,0,0,0,1,...,0,0,0,0,0,0,False,False,166.666667,283.602339
5,Ayurveda,-999.0,True,8.0,Porur,Chennai,0,0,0,1,...,0,0,0,0,0,0,False,False,268.000000,283.602339
6,Homeopath,-999.0,True,42.0,Karol Bagh,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,452.777778,363.006757
7,Dentist,99.0,False,10.0,Arekere,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,208.333333,328.842607
8,General Medicine,-999.0,True,14.0,Old City,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,175.000000,307.507886
9,Dentist,-999.0,True,23.0,Athani,Ernakulam,0,0,0,0,...,0,0,0,0,0,0,False,False,100.000000,188.431373
10,ENT Specialist,-999.0,True,5.0,Thousand Lights,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,485.714286,283.602339
11,Ayurveda,-999.0,True,7.0,Somajiguda,Hyderabad,0,0,0,1,...,0,0,0,0,0,0,False,False,416.666667,307.507886
12,Dentist,98.0,False,9.0,Coimbatore Racecourse,Coimbatore,0,0,0,0,...,0,0,0,0,0,0,False,False,256.250000,154.298246
13,Dentist,-999.0,True,21.0,Jubilee Hills,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,397.500000,307.507886
14,ENT Specialist,-999.0,True,12.0,Kondli,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,325.000000,363.006757
15,General Medicine,-999.0,True,10.0,Saroor Nagar,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,241.666667,307.507886
16,ENT Specialist,-999.0,True,24.0,Tambaram West,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,177.777778,283.602339
17,Homeopath,-999.0,True,5.0,Purasawakkam,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,235.714286,283.602339
18,ENT Specialist,79.0,False,19.0,KPHB,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,354.285714,307.507886
19,General Medicine,100.0,False,19.0,HSR Layout,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,341.986667,328.842607
20,Dentist,100.0,False,21.0,Pollachi,Coimbatore,0,0,0,0,...,0,0,0,0,0,0,False,False,128.571429,154.298246
21,ENT Specialist,-999.0,True,14.0,Vasundhra Enclave,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,400.000000,363.006757
22,General Medicine,-999.0,True,41.0,Chembur,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,361.071429,308.292863
23,General Medicine,-999.0,True,31.0,Thammanam,Ernakulam,0,0,0,0,...,0,0,0,0,0,0,False,False,150.000000,188.431373
24,Dermatologists,-999.0,True,23.0,Andheri,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,325.000000,308.292863
25,Dentist,-999.0,True,5.0,Pattom,Thiruvananthapuram,0,0,0,0,...,0,0,0,0,0,0,False,False,165.000000,167.267442
26,General Medicine,100.0,False,25.0,HSR Layout,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,341.986667,328.842607
27,General Medicine,95.0,False,12.0,Kukatpally,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,304.411765,307.507886
28,Dentist,-999.0,True,16.0,Vadavalli,Coimbatore,0,0,0,0,...,0,0,0,0,0,0,False,False,116.666667,154.298246
29,Dermatologists,97.0,False,15.0,Defence Colony,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,333.333333,363.006757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5931,General Medicine,99.0,False,13.0,Richards Town,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,250.000000,328.842607
5932,Dentist,-999.0,True,9.0,Singanallur,Coimbatore,0,0,0,0,...,0,0,0,0,0,0,False,False,128.571429,154.298246
5933,Homeopath,96.0,False,21.0,Banashankari 3rd Stage,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,261.363636,328.842607
5934,Homeopath,-999.0,True,19.0,Mazgaon,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,268.750000,308.292863
5935,Dentist,99.0,False,12.0,HSR Layout,Bangalore,0,1,0,0,...,0,0,0,0,0,0,False,False,341.986667,328.842607
5936,Homeopath,100.0,False,34.0,Chembur,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,361.071429,308.292863
5937,Homeopath,96.0,False,19.0,Marathahalli,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,299.743590,328.842607
5938,General Medicine,-999.0,True,36.0,Rajarajeshwarinagar,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,278.571429,328.842607
5939,Homeopath,-999.0,True,7.0,Mulund East,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,325.000000,308.292863
5940,Dermatologists,80.0,False,40.0,Malad East,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,200.000000,308.292863
5941,Homeopath,-999.0,True,30.0,IP Extension,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,300.000000,363.006757
5942,General Medicine,90.0,False,51.0,HSR Layout,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,341.986667,328.842607
5943,Dentist,95.0,False,3.0,Koramangala,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,355.714286,328.842607
5944,ENT Specialist,-999.0,True,2.0,Tambaram West,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,177.777778,283.602339
5945,Dentist,-999.0,True,4.0,Valasaravakkam,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,242.857143,283.602339
5946,Dentist,99.0,False,12.0,Dwarka,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,399.264706,363.006757
5947,Homeopath,-999.0,True,6.0,Malleswaram,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,321.276596,328.842607
5948,Ayurveda,-999.0,True,15.0,Govandi,Mumbai,0,0,0,1,...,0,0,0,0,0,0,False,False,87.500000,308.292863
5949,Homeopath,-999.0,True,8.0,Borivali West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,351.903846,308.292863
5950,Dermatologists,100.0,False,4.0,Konanakunte,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,275.000000,328.842607
5951,Dentist,-999.0,True,4.0,HAL,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,200.000000,328.842607
5952,General Medicine,-999.0,True,47.0,Bhandup West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,268.518519,308.292863
5953,Homeopath,92.0,False,35.0,Malleswaram,Bangalore,0,1,0,0,...,0,0,0,0,0,0,False,False,321.276596,328.842607
5954,Homeopath,-999.0,True,31.0,Adarsh Nagar,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,270.000000,363.006757
5955,Homeopath,-999.0,True,10.0,Vijaynagar,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,350.000000,363.006757
5956,ENT Specialist,98.0,False,19.0,Basavanagudi,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,340.625000,328.842607
5957,General Medicine,-999.0,True,33.0,Nungambakkam,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,378.846154,283.602339
5958,General Medicine,97.0,False,41.0,Greater Kailash Part 2,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,416.666667,363.006757
5959,General Medicine,90.0,False,15.0,Vileparle West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,253.488372,308.292863
5960,Dentist,100.0,False,17.0,Pitampura,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,394.444444,363.006757

In [139]:
test

,0,1,2,3,4,5,6,7,8,9,...,250,251,252,253,254,255,256,257,258,259
0,General Medicine,-999.0,True,35.0,Ghatkopar East,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,333.684211,308.292863
1,ENT Specialist,-999.0,True,31.0,West Marredpally,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,361.111111,307.507886
2,Dermatologists,70.0,False,40.0,KK Nagar,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,271.428571,283.602339
3,Ayurveda,-999.0,True,0.0,New Ashok Nagar,Delhi,0,0,0,1,...,0,0,0,0,0,0,False,False,233.333333,363.006757
4,Dentist,100.0,False,16.0,Kanakpura Road,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,345.000000,328.842607
5,Dentist,90.0,False,14.0,Velachery,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,305.000000,283.602339
6,ENT Specialist,94.0,False,23.0,Frazer Town,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,330.000000,328.842607
7,Dentist,94.0,False,9.0,Attapur,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,273.684211,307.507886
8,Ayurveda,99.0,False,11.0,Banashankari,Bangalore,0,0,1,1,...,0,0,0,0,0,0,False,False,308.333333,328.842607
9,Homeopath,-999.0,True,44.0,Mayur Vihar Ph-I,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,347.727273,363.006757
10,Dentist,100.0,False,4.0,Erragadda,Hyderabad,0,0,0,0,...,0,0,0,0,0,1,False,False,358.333333,307.507886
11,General Medicine,-999.0,True,34.0,Gandhipuram,Coimbatore,0,0,0,0,...,0,0,0,0,0,0,False,False,138.888889,154.298246
12,Dermatologists,98.0,False,11.0,Kemps Corner,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,227.272727,308.292863
13,Dermatologists,99.0,False,13.0,Banjara Hills,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,383.593750,307.507886
14,ENT Specialist,-999.0,True,4.0,Madandapuram,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,200.000000,283.602339
15,Dentist,-999.0,True,4.0,Mukherjee Nagar,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,133.333333,363.006757
16,Dermatologists,87.0,False,16.0,Tis Hazari,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,550.000000,363.006757
17,ENT Specialist,64.0,False,28.0,Banashankari 2nd Stage,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,346.875000,328.842607
18,Dentist,-999.0,True,6.0,Nagawara,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,271.428571,328.842607
19,Dermatologists,90.0,False,32.0,Basavanagudi,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,340.625000,328.842607
20,Homeopath,-999.0,True,11.0,Dadar,Mumbai,0,1,0,0,...,0,0,0,0,0,0,False,False,480.000000,308.292863
21,Dentist,-999.0,True,3.0,Kattakada,Thiruvananthapuram,0,0,0,0,...,0,0,0,0,0,0,False,False,100.000000,167.267442
22,Dermatologists,-999.0,True,8.0,Villivakkam,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,221.428571,283.602339
23,General Medicine,100.0,False,13.0,Begumpet,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,272.727273,307.507886
24,General Medicine,-999.0,True,43.0,Kottivakkam,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,266.666667,283.602339
25,ENT Specialist,-999.0,True,27.0,Jeedimetla,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,160.000000,307.507886
26,Dentist,100.0,False,22.0,Gachibowli,Hyderabad,0,0,0,0,...,0,0,0,1,0,0,False,False,411.290323,307.507886
27,Dentist,96.0,False,8.0,Chromepet,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,183.333333,283.602339
28,General Medicine,-999.0,True,25.0,Mulund West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,340.740741,308.292863
29,ENT Specialist,-999.0,True,4.0,Bellandur,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,342.592593,328.842607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,Dentist,100.0,False,6.0,Andheri West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,364.714286,308.292863
1955,General Medicine,-999.0,True,46.0,Tilak Nagar,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,330.000000,363.006757
1957,Dentist,100.0,False,8.0,KPHB,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,354.285714,307.507886
1958,ENT Specialist,53.0,False,40.0,Millers Road,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,633.333333,328.842607
1959,General Medicine,-999.0,True,43.0,Vileparle West,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,253.488372,308.292863
1960,Dentist,95.0,False,29.0,Punjagutta,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,422.727273,307.507886
1961,Homeopath,-999.0,True,2.0,Malleswaram,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,321.276596,328.842607
1962,General Medicine,100.0,False,12.0,Rohini,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,316.216216,363.006757
1963,Homeopath,-999.0,True,3.0,Habsiguda,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,300.000000,307.507886
1964,Dentist,-999.0,True,8.0,Ramanathapuram,Coimbatore,0,1,0,0,...,0,0,0,0,0,0,False,False,113.636364,154.298246
1966,General Medicine,-999.0,True,24.0,Tambaram,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,221.250000,283.602339
1967,Dentist,98.0,False,13.0,Yelahanka,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,329.333333,328.842607
1968,General Medicine,96.0,False,23.0,Indiranagar,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,397.916667,328.842607
1969,Ayurveda,-999.0,True,32.0,Chembur,Mumbai,0,0,1,1,...,0,0,0,0,0,0,False,False,361.071429,308.292863
1970,Dentist,-999.0,True,7.0,Sundarapuram,Coimbatore,0,1,0,0,...,0,0,0,0,0,0,False,False,200.000000,154.298246
1971,ENT Specialist,-999.0,True,26.0,Okhla,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,244.444444,363.006757
1972,Dermatologists,93.0,False,15.0,Moti Nagar,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,233.333333,307.507886
1973,Dermatologists,-999.0,True,4.0,Velachery,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,305.000000,283.602339
1974,ENT Specialist,-999.0,True,19.0,Munirka,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,460.000000,363.006757
1975,General Medicine,-999.0,True,26.0,Panchsheel Park,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,346.153846,363.006757
1976,ENT Specialist,84.0,False,11.0,Miyapur,Hyderabad,0,0,0,0,...,0,0,0,0,0,0,False,False,246.153846,307.507886
1977,General Medicine,-999.0,True,28.0,Panchsheel Park,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,346.153846,363.006757
1978,Dentist,-999.0,True,15.0,Prabhadevi,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,280.000000,308.292863
1979,Dentist,100.0,False,17.0,Powai,Mumbai,0,0,0,0,...,0,0,0,0,0,0,False,False,442.142857,308.292863
1980,Dentist,98.0,False,18.0,Velachery,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,305.000000,283.602339
1981,Dermatologists,-999.0,True,8.0,Lajpat Nagar III,Delhi,0,0,0,0,...,0,0,0,0,0,0,False,False,450.000000,363.006757
1982,Ayurveda,-999.0,True,10.0,Basavanagudi,Bangalore,0,0,0,1,...,0,0,0,0,0,0,False,False,340.625000,328.842607
1984,General Medicine,-999.0,True,9.0,Porur,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,268.000000,283.602339
1985,Dentist,98.0,False,12.0,Arekere,Bangalore,0,0,0,0,...,0,0,0,0,0,0,False,False,208.333333,328.842607
1986,Dermatologists,-999.0,True,8.0,Pallikaranai,Chennai,0,0,0,0,...,0,0,0,0,0,0,False,False,356.666667,283.602339

In [140]:
from sklearn.preprocessing import LabelEncoder
cols=(0,2,4,5,256,257)
for c in cols:
    lbl=LabelEncoder()
    lbl.fit(list(X[c].values))
    X[c]=lbl.transform(list(X[c].values))
    test[c]=lbl.transform(list(test[c].values))

In [141]:
#df["Qual1"]

In [142]:
#X=df.drop("Fees",axis=1)
#y=df["Fees"]

In [143]:
#X

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rfc=RandomForestRegressor(n_estimators=1000)

In [ ]:
rfc.fit(X,y)

In [ ]:
lol=rfc.predict(test)

In [ ]:
#lol

In [ ]:
#y

In [144]:
import xgboost as xgb
xgb = xgb.XGBRegressor(learning_rate=0.05,n_estimators= 3000,
                    silent=True, nthread=1)

In [145]:
xgb.fit(X,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.05, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=3000,
       n_jobs=1, nthread=1, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [146]:
xgbpredict1=xgb.predict(test)

In [147]:
len(xgbpredict1)

1904

In [148]:
def rmsle(p, a):
    sum = 0
    for i in  range(0,len(p)):
        sum += math.pow(math.log(float(p[i]) + 1) - math.log(float(a[i]) + 1),2)
    sum = sum * (1/len(p))
    return float(math.sqrt(sum))

In [149]:
#rmsle(haha,y)

In [150]:
import math

In [155]:
int(round(260.7,-1))

260

In [ ]:
haha=[]
for i in range(0,len(lol)):
    lel=(round(lol[i]/50)*50)
    haha.append(lel)

In [ ]:
lol[0]

In [ ]:
(round(lol[i]/50)*50)

In [ ]:
params={'bootstrap': [True, False],
 'max_depth': [10, 50, 80, 100, None],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 1000, 1800, 2000]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.model_selection import KFold

In [ ]:
folds = 3
param_comb = 5

skf = KFold(n_splits=folds, shuffle = True, random_state = 1001)

random_search = RandomizedSearchCV(rfc, param_distributions=params, n_iter=param_comb, scoring=rmsle, n_jobs=4, cv=skf.split(X,y), verbose=3, random_state=1001 )

In [ ]:
random_search.fit(X, y)

## For unknown location

In [ ]:
test1

In [ ]:
X1

In [156]:
test1 = test1.drop([9,'LOCDmean'], axis =1)

In [157]:
X1 = X1.drop([10, 'LOCDmean'], axis =1)

In [158]:
X1.columns=range(X1.shape[1])
test1.columns=range(test1.shape[1])

In [159]:
from sklearn.preprocessing import LabelEncoder
cols=(0,2,4,5,255,256)
for c in cols:
    lbl=LabelEncoder()
    lbl.fit(list(X1[c].values))
    X1[c]=lbl.transform(list(X1[c].values))
    test1[c]=lbl.transform(list(test1[c].values))

In [ ]:
rfc.fit(X1,y)

In [ ]:
samekey = rfc.predict(test1)

In [160]:
xgb.fit(X1, y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.05, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=3000,
       n_jobs=1, nthread=1, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [161]:
xgbpredict2 = xgb.predict(test1)

In [219]:
res1 = pd.DataFrame(el1, index = test.index)

In [220]:
res2 = pd.DataFrame(el2, index = test1.index)

In [221]:
res = pd.concat([res1, res2], axis = 0).sort_index(ascending=True)

In [222]:
res = res.rename(columns={0:"Fees"})

In [223]:
res.head()

         Fees
0  319.261632
1  343.748874
2  279.608934
3  195.961252
4  328.038368

In [224]:
res.shape

(1987, 1)

In [225]:
res.to_excel('Fees6.xlsx')

In [174]:
import lightgbm as lgb

In [175]:
lgb = lgb.LGBMRegressor(n_estimators = 3000)

In [176]:
lgb.fit(X,y)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
       learning_rate=0.1, max_depth=-1, min_child_samples=20,
       min_child_weight=0.001, min_split_gain=0.0, n_estimators=3000,
       n_jobs=-1, num_leaves=31, objective=None, random_state=None,
       reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
       subsample_for_bin=200000, subsample_freq=0)

In [177]:
lgbpred1=lgb.predict(test)

In [178]:
lgb.fit(X1,y)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
       learning_rate=0.1, max_depth=-1, min_child_samples=20,
       min_child_weight=0.001, min_split_gain=0.0, n_estimators=3000,
       n_jobs=-1, num_leaves=31, objective=None, random_state=None,
       reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
       subsample_for_bin=200000, subsample_freq=0)

In [179]:
lgbpred2 = lgb.predict(test1)

In [187]:
from sklearn.neighbors import KNeighborsRegressor

In [188]:
knn = KNeighborsRegressor(n_neighbors=4)

In [189]:
knn.fit(X,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=4, p=2,
          weights='uniform')

In [190]:
knnpred1 = knn.predict(test)

In [192]:
knn.fit(X1,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=4, p=2,
          weights='uniform')

In [193]:
knnpred2 = knn.predict(test1)

In [ ]:
print('\n All results:')
print(random_search.cv_results_)
print('\n Best estimator:')
print(random_search.best_estimator_)
print('\n Best normalized gini score for %d-fold search with %d parameter combinations:' % (folds, param_comb))
print(random_search.best_score_ * 2 - 1)
print('\n Best hyperparameters:')
print(random_search.best_params_)

In [201]:
from sklearn.linear_model import Lasso

In [202]:
las = Lasso()

In [203]:
las.fit(X,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [204]:
las1 = las.predict(test)

In [205]:
las.fit(X1,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [206]:
las2= las.predict(test1)

In [213]:
from sklearn.linear_model import ElasticNet

In [214]:
el = ElasticNet()

In [215]:
el.fit(X,y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [216]:
el1 = el.predict(test)

In [217]:
el.fit(X1,y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [218]:
el2 = el.predict(test1)